# 摄谱仪
[spec_a_vph]
sn = AB0MZAT1
# 单光谱仪
[spec_a_n1]
sn = OMS23003
# 双级连
[spec_a_n2]
sn = OM222002
# 三级联
[spec_a_n3]
sn = omni315001
# 180d 单谱仪或三级联的1-2级
[spec_a_180d]
sn = omni315001

# 单光谱仪
[spec_b_n1]
sn = OM222002
# 双级连
[spec_b_n2]
sn = omni315001
# 180d
[spec_b_180d]
sn = omni315001

# 自制
[dcs300pa]
sn = DAQ14018
[lockin]
sn = COM53
[dcs210pc]
sn = DAQ14018

# Keithley/Keysight 源表
[meter]
sn = 0x02

[andor]
cool = true
temp = -60.000000
flip = 0
reverse = 0
[andor2]
cool = true
temp = -60
reverse = 1
[mity]
sn = auto
[greateyes]
sn = auto
[oto]
sn = auto
[dccd]
sn = DFN22003
cool = true
temp = -10.000000
reverse = 0
[toucan]
temp = -55.000000
flip = 0
reverse = 0
bad = []