[service]
# [root]
# websocket = 00, tcp = 01
protocol = 00

# logfile = logs/httpd.log
# loglevel = [VERBOSE,DEBUG,INFO,WARN,ERROR,FATAL,SILENT]
loglevel = INFO
log_remain_days = 3
log_filesize = 64M

# worker_processes = auto # auto = ncpu
worker_processes = auto

# http/websocket server
http_port = 8082
https_port = 8443
# base_url = /api/v1
document_root = root/930
home_page = index.html
#error_page = error.html
#index_of = /downloads/

# SSL/TLS
# ssl_certificate = cert/server.crt
# ssl_privatekey = cert/server.key
# ssl_ca_certificate = cert/cacert.pem

# tcp server
tcp_port = 8091

[remote]
url = ws://42.96.138.123/TestWebSocket/webSocket/zolixDevicezolixBJ0001

# system
[system]
sys_00 = iSpecScan
sys_01 = QE_IPCE
sys_02 = IV_Test
sys_03 = OmniWin
sys_04 = zolix_software
sys_05 = Finder930Dll
selected = 02
